### PR TITLE
add search and recent json api

### PR DESCRIPTION
**Pull request by merrickluo**
For #9

### CODE REVIEW

**Comment by bitinn** [comment]
Thx, and lgtm in general, a few things I would fix:
1. rename api to GET `/api/shots`, without `q`, defaults to recent shots, otherwise do a search.
2. make sure you handle cases where `results` are `undefined`, as you called it with `map`. Though if you do item 1, you wouldn't have this problem.

**Comment by merrickluo** [comment]
How about now, I really don't know much about js...

**Comment by bitinn** [comment]
ah no worries, I will take it from here

**Comment by bitinn** [comment]
This is now deployed, please note the api return data using slightly different attributes.

screen shot 2016-04-16 at 3 02 33 pm

**Comment by merrickluo** [comment]
Copy that.

**Pull request merged**
